version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: asana-scripts-app-likes
    volumes:
      - .:/opt/app
    command: [ 'python', '/opt/app/cli.py', 'ui' ]
    working_dir: '/opt/app'
