version: '3.3'

services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
    container_name: cg22-needforgirl-tests
    volumes:
      - .:/opt/app
    command: [ 'python', '-m', 'pytest', '/opt/app/tests' ]
    working_dir: '/opt/app'