PNM_BYTES_PER_PIXEL = {'P5': 1, 'P6': 3}
PNM_SUPPORTED_FORMATS = tuple(PNM_BYTES_PER_PIXEL.keys())
P5 = PNM_SUPPORTED_FORMATS[0]
P6 = PNM_SUPPORTED_FORMATS[1]
COLOR_MODELS = {'RGB': 1, 'HSL': 2, 'HSV': 3, 'YCbCr601': 4, 'YCbCr709': 5, 'YCoCg': 6, 'CMY': 7}
DITHERING_ALGORITHMS = {
    'NONE': 1, 'RANDOM': 2, 'ORDERED_8X8': 3, 'FLOYD_STEINBERG': 4, 'ATKINSON': 5
}
SCALING_ALGORITHMS = {
    'NONE': 1, 'NEAREST_NEIGHBOR': 2, 'BILINEAR': 3, 'LANCZOS3': 4, 'BC_SPLINE': 5
}
